# Generated by Django 6.1 on 2026-09-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='thumbnail',
        ),
    ]
