# Generated by Django 6.1 on 2026-09-15 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_education_description_remove_skills_ended_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(max_length=255)),
                ('project_url', models.URLField(blank=True)),
                ('project_image_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary'), ('non-formal', 'Non-Formal')], default='non-formal', max_length=20),
        ),
    ]
