# Generated by Django 6.1 on 2026-09-22 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_alter_education_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_education', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_experience', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skills',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
